{% set name = "pyfoomb" %}
{% set version = "2.17.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/MicroPhen/pyFOOMB/archive/v{{ version }}.tar.gz
  sha256: 0b5afb1d6fc629559ea6c37be667810b5dea8b86759089b0cc0fa5a4c1557a6a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - numpy
    - scipy
    - joblib
    - pandas >=0.24
    - openpyxl
    - matplotlib-base
    - seaborn-base
    - psutil
    - pip
    - assimulo
    - pygmo >=2.14

test:
  imports:
    - pyfoomb

about:
  home: https://github.com/MicroPhen/pyFOOMB
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: pyFOOMB is a framework for object oriented modelling of bioprocesses
  description: |
    Intented application is the acessible modelling of simple to medium complex 
    bioprocess models, by programmatic means. In contrast to 'full-blown' software 
    suites, pyFOOMB can be used by scientists with little programming skills in the 
    easy-access language Python.
  dev_url: https://github.com/MicroPhen/pyFOOMB

extra:
  recipe-maintainers:
    - MicroPhen
    - kossikater
    - Beaker034
